server:
  port: 6868 #服务端口
spring:
  application:
    name: eureka-server-4peter # 应用名称，会在Eureka中显示
eureka:
  client:
    registerWithEureka: true #false时不注册。是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetchRegistry: true #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/ #http://127.0.0.1:${server.port}/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 10000 # 扫描失效服务的间隔时间（缺省为60*1000ms）